- block:
    - name: Install vsftpd
      apt:
        name: vsftpd
        state: present
    - name: Start vsftpd
      service:
        name: vsftpd
        state: started
    - name: Enable vsftpd
      service:
        name: vsftpd
        enabled: yes
    - name: Configure vsftpd
      template:
        src: template/vsftpd/vsftpd.conf.j2
        dest: /etc/vsftpd.conf
    - name: Restart vsftpd
      service:
        name: vsftpd
        state: restarted
  become: yes
  become_user: root