block:
- name: Install python
  apt:
    name: python
    state: present

- name: Install python-pip
  apt:
    name: python-pip
    state: present

- name: Install python3
  apt:
    name: python3
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install python3-venv
  apt:
    name: python3-venv
    state: present

- name: Install python3-dev
  apt:
    name: python3-dev
    state: present

- name: Install python3-setuptools
  apt:
    name: python3-setuptools
    state: present

- name: Install python3-wheel
  apt:
    name: python3-wheel
    state: present

- name: Install python3-apt
  apt:
    name: python3-apt
    state: present

- name: Install discord.py
  pip:
    name: discord.py
    state: present

- name: Install any requirements
  pip:
    requirements: files/python/requirements.txt
    executable: pip3
    state: present

become: yes
become_user: root