- name: Using a template to change the current keyboard and apply changes
  block:
    - name: Apply keyboard template
      template:
        src: "{{ ssh_templates }}/keyboard.j2"
        dest: "/etc/default/keyboard"
        mode: "0644"
        
    - name: Apply keyboard configuration
      command: setupcon
  tags: keyboard
